# https://www.gitpod.io/docs/config-gitpod-file

image: gitpod/workspace-full

ports:
  - port: 3000
    onOpen: notify
  - port: 3001
    onOpen: notify
  - port: 5173
    onOpen: notify

tasks:
  - init: dependencies install
    command: |
      npm install -global pnpm
      pnpm install
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - rangav.vscode-thunder-client
    - Vue.volar
    - dracula-theme.theme-dracula
    - PKief.material-icon-theme
