# https://www.gitpod.io/docs/config-gitpod-file

image: gitpod/workspace-full

ports:
  - port: 3000
    onOpen: open-browser
  - port: 3001
    onOpen: open-browser
  - port: 5173
    onOpen: open-browser

tasks:
  - init: npm install -g pnpm
    command: |
      pnpm install
      pnpm --filter back-end run prisma:setup
      pnpm run -recursive dev
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - rangav.vscode-thunder-client
    - Vue.volar
    - dracula-theme.theme-dracula
    - PKief.material-icon-theme
