# https://www.gitpod.io/docs/config-gitpod-file

image: gitpod/workspace-full

ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: open-preview
  - port: 5173
    onOpen: open-preview

tasks:
  - init: npm install -g pnpm
    command: |
      pnpm install
      pnpm run setup
      pnpm dev
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - rangav.vscode-thunder-client
    - Vue.volar
    - dracula-theme.theme-dracula
    - PKief.material-icon-theme
